// framework/views/angular-app/src/app/components/product-list/product-list.component.ts
import { Component, OnInit } from '@angular/core';
import ProductManagementHttpAdapter from '@framework/output/httpClient/ProductManagementHttpAdapter';
import { mirageHttpClient } from '@framework/output/httpClient/repository/mirageServer';
import ProductManagementInputPort from '@application/ports/input/ProductManagementInputPort';
import Product from '@domain/Product';
@Component({
  selector: 'app-product-list',
  templateUrl: './product-list.component.html',
  styleUrls: ['./product-list.component.css']
})
export class ProductListComponent implements OnInit {
  products: Product[] = [];

  ngOnInit(): void {
    const productManagementInputPort = new ProductManagementInputPort(new ProductManagementHttpAdapter(mirageHttpClient));
    productManagementInputPort.getProducts().then((products) => {
      this.products = products;
    });
  }

}

<div *ngFor="let product of products">
  <h1>{{product.title}}</h1>
  <p>{{product.price}}</p>
</div>

// framework/views/next-react-app/src/components/ProductList.tsx
"use client";
import React, { useEffect, useState } from 'react'
import ProductManagementInputPort from '@application/ports/input/ProductManagementInputPort'
import ProductManagementHttpAdapter from '@framework/output/httpClient/ProductManagementHttpAdapter'
import Product from '@domain/Product'
import {mirageHttpClient} from '@framework/output/httpClient/repository/mirageServer';


export default function ProductList() {
  const [products, setProducts] = useState<Product[]>([]);

  useEffect(() => {
    const productService = new ProductManagementInputPort(new ProductManagementHttpAdapter(mirageHttpClient))
    productService.getProducts().then((products: Product[]) => setProducts(products))
  }, [])

  return (
    <div className='product-list'>
      {products.map(product => <div key={product.id.getId()} className='product'>{product.title}</div>)}
    </div>
  )
}
